### ISSUE TITLE
[blog] [styling] color palette

### ISSUE THREAD

**Issue by lorenzogm** [valtech-ch/frontend-playground#12]

**Comment by SgiobairOg** [comment]
Valtech Global Styles:

White R255 G255 B255
Black R0 G0 B0
Blue R0 G189 B250
Connected Cyan R0 G255 B250
Disruptive Rose R255 G27 B120
Transformative Turquoise R13 G253 B180
Agile Yellow R255 G240 B17

![screenshot-2](https://user-images.githubusercontent.com/6902508/87157427-876f1400-c2be-11ea-8086-c21253376777.png)
![screenshot-3](https://user-images.githubusercontent.com/6902508/87157439-8b029b00-c2be-11ea-8d82-193d42361c3d.png)
![screenshot-1](https://user-images.githubusercontent.com/6902508/87157458-90f87c00-c2be-11ea-9cf4-f477ab0229ef.png)
